### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by safaci2000** [OSAlt/sysadmin#1]
Get a valid SSL certificate on server for both the wiki and the website.  Force SSL traffic for all requests whether it requires encryption or not.

**Comment by drahamim** [comment]
We could do some sort of automated Lets encrypt SSL certs.

**Comment by mjeveritt** [comment]
The beta domain may still be WIP, but the wiki is live with a self-updating LE cert using dehydrated script.

I'll happily fix beta as/when we're ready if needed.
